#!/usr/bin/env node
/**
 * Migration Script: Add virtualMechanicSummary field
 *
 * Adds the new virtualMechanicSummary TEXT field to the vehicles table.
 * This field stores the concise 3-5 bullet point summary generated by AI.
 */

import { createClient } from '@libsql/client';
import { WorkspaceUtils } from '@car-finder/services';
import * as path from 'path';

async function migrate() {
  console.log('🔄 Starting migration: Add virtualMechanicSummary field...');

  // Load environment
  WorkspaceUtils.loadEnvFromRoot();
  const workspaceRoot = WorkspaceUtils.findWorkspaceRoot();

  // Get database URL and ensure it's an absolute path
  let dbUrl = process.env.DATABASE_URL || `file:${workspaceRoot}/data/vehicles.db`;

  // If the URL uses a relative file path, make it absolute
  if (dbUrl.startsWith('file:') && !dbUrl.includes('://')) {
    const filePath = dbUrl.substring(5); // Remove 'file:' prefix
    if (!path.isAbsolute(filePath)) {
      dbUrl = `file:${path.join(workspaceRoot, filePath)}`;
    }
  }

  const client = createClient({ url: dbUrl });

  try {
    // Check if column already exists
    const tableInfo = await client.execute("PRAGMA table_info(vehicles)");
    const columnExists = tableInfo.rows.some((row: any) => row.name === 'virtualMechanicSummary');

    if (columnExists) {
      console.log('✅ Column virtualMechanicSummary already exists. Migration skipped.');
      return;
    }

    // Add the new column
    await client.execute(`
      ALTER TABLE vehicles
      ADD COLUMN virtualMechanicSummary TEXT
    `);

    console.log('✅ Successfully added virtualMechanicSummary column to vehicles table');

    // Verify the column was added
    const verifyTableInfo = await client.execute("PRAGMA table_info(vehicles)");
    const verifyColumn = verifyTableInfo.rows.find((row: any) => row.name === 'virtualMechanicSummary');

    if (verifyColumn) {
      console.log('✅ Verification successful: virtualMechanicSummary column exists');
      console.log(`   Type: ${verifyColumn.type}, Nullable: ${verifyColumn.notnull === 0 ? 'YES' : 'NO'}`);
    } else {
      console.error('❌ Verification failed: Column not found after migration');
      process.exit(1);
    }

  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    client.close();
  }

  console.log('✅ Migration completed successfully');
}

// Run migration if executed directly
if (require.main === module) {
  migrate().catch(console.error);
}

export { migrate };
